/**
 * `next-env.d.ts` carries this declaration, but it is generated by `next build`
 * and gitignored, so a bare `pnpm typecheck` on a clean checkout has nothing
 * describing a side-effect stylesheet import. Declaring it here keeps
 * `noUncheckedSideEffectImports` on, which still catches a side-effect import
 * of a module that does not exist at all.
 */
declare module '*.css';
